version: '2.2'
services:
  pg_analytics:
    image: postgres:12
    environment:
      POSTGRES_DB: analytics
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d analytics -U admin" ]
      interval: 30s
      timeout: 30s
      retries: 3
  hop:
    image: apache/hop-web:latest
    ports:
      - "8080:8080"
    volumes:
      - ./hop_files:/usr/local/tomcat/webapps/ROOT/config/projects/default/:rw
    depends_on:
      pg_analytics:
        condition: service_healthy
  metabase:
    image: metabase/metabase
    environment:
      MB_DB_FILE: "/tmp/metabase.db"
    ports:
      - "3000:3000"
    volumes:
      - .metabase_db:/tmp/metabase.db:rw

